# Generated by Django 2.0 on 2017-12-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbtBuildServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='modified_data',
            new_name='modified_date',
        ),
    ]
