# Generated by Django 2.0 on 2017-12-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbtBuildServer', '0002_auto_20171211_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pub_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='modified_date',
            new_name='update_date',
        ),
    ]
