# Generated by Django 2.0 on 2017-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbtBuildServer', '0005_auto_20171211_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeta',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='usermeta',
            name='update_date',
        ),
        migrations.AddField(
            model_name='usermeta',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
